package com.xhu.xuyi.entity;
// Generated 2016-3-16 21:42:57 by Hibernate Tools 3.5.0.Final

/**
 * Feedtime generated by hbm2java
 */
@SuppressWarnings("serial")
public class FeedTime implements java.io.Serializable {

	private String feedTime;
	private String feedValue;

	public FeedTime() {
	}

	public FeedTime(String feedTime) {
		this.feedTime = feedTime;
	}

	public FeedTime(String feedTime, String feedValue) {
		this.feedTime = feedTime;
		this.feedValue = feedValue;
	}

	public String getFeedTime() {
		return this.feedTime;
	}

	public void setFeedTime(String feedTime) {
		this.feedTime = feedTime;
	}

	public String getFeedValue() {
		return this.feedValue;
	}

	public void setFeedValue(String feedValue) {
		this.feedValue = feedValue;
	}

}
