package com.xhu.xuyi.entity;
// Generated 2016-3-16 21:42:57 by Hibernate Tools 3.5.0.Final

/**
 * User generated by hbm2java
 */
@SuppressWarnings("serial")
public class User implements java.io.Serializable {

	private String userId;
	private String userName;
	private String password;
	private String userIp;
	private Integer userPort;

	public User() {
	}

	public User(String userId) {
		this.userId = userId;
	}

	public User(String userId, String userName, String password, String userIp, Integer userPort) {
		this.userId = userId;
		this.userName = userName;
		this.password = password;
		this.userIp = userIp;
		this.userPort = userPort;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	public Integer getUserPort() {
		return this.userPort;
	}

	public void setUserPort(Integer userPort) {
		this.userPort = userPort;
	}

}
