package com.xhu.xuyi.entity;
// Generated 2016-3-16 21:42:57 by Hibernate Tools 3.5.0.Final

/**
 * UserOxFe generated by hbm2java
 */
@SuppressWarnings("serial")
public class UserOxFe implements java.io.Serializable {

	private String userId;
	private String oxygenTime;
	private String feedTime;

	public UserOxFe() {
	}

	public UserOxFe(String userId, String oxygenTime, String feedTime) {
		this.userId = userId;
		this.oxygenTime = oxygenTime;
		this.feedTime = feedTime;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getOxygenTime() {
		return this.oxygenTime;
	}

	public void setOxygenTime(String oxygenTime) {
		this.oxygenTime = oxygenTime;
	}

	public String getFeedTime() {
		return this.feedTime;
	}

	public void setFeedTime(String feedTime) {
		this.feedTime = feedTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserOxFe))
			return false;
		UserOxFe castOther = (UserOxFe) other;

		return ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
				&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getOxygenTime() == castOther.getOxygenTime()) || (this.getOxygenTime() != null
						&& castOther.getOxygenTime() != null && this.getOxygenTime().equals(castOther.getOxygenTime())))
				&& ((this.getFeedTime() == castOther.getFeedTime()) || (this.getFeedTime() != null
						&& castOther.getFeedTime() != null && this.getFeedTime().equals(castOther.getFeedTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getOxygenTime() == null ? 0 : this.getOxygenTime().hashCode());
		result = 37 * result + (getFeedTime() == null ? 0 : this.getFeedTime().hashCode());
		return result;
	}

}
